apiVersion: v1
kind: Service
metadata:
  name: clean-architecture-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: clean-architecture